### ISSUE TITLE
token-validation-spring: dersom metadata-endepunktet er utilgjengelig under oppstart så feiler hele applikasjonen i å starte

### ISSUE THREAD

**Issue by alexraknesnav** [navikt/token-support#124]
Dersom metadata-endepunktet er utilgjengelig under oppstart av applikasjonen så lastes ikke Spring-konfigurasjonen og den feiler med følgende exception: `org.springframework.context.ApplicationContextException: Unable to start web server`.

Dette skjer dersom man bruker følgende autokonfigurasjon med følgende annotering: `@EnableJwtTokenValidation`.

Selv om dette kanskje er et sjeldent scenario i prod så kan det lett forekomme under integrasjonstesting dersom man bruker docker-compose og mock-idp container starter opp tregere enn applikasjonen som er under test.

Årsaken er følgende linje i `IssuerConfiguration.java` som forutsetter at metadata-endepunktet er oppe:

```
return OIDCProviderMetadata.parse(resourceRetriever.retrieveResource(url).getContent());
```

Et fullstendig stacktrace følger under:

```
k9-infotrygd-feed           | 2020-03-05 14:54:11.626 ERROR 6 --- [           main] o.s.boot.SpringApplication               : Application run failed
k9-infotrygd-feed           | 
k9-infotrygd-feed           | org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
k9-infotrygd-feed           | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:156) ~[spring-boot-2.3.0.M2.jar!/:2.3.0.M2]
k9-infotrygd-feed           | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544) ~[spring-context-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.3.0.M2.jar!/:2.3.0.M2]
k9-infotrygd-feed           | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot-2.3.0.M2.jar!/:2.3.0.M2]
k9-infotrygd-feed           | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) ~[spring-boot-2.3.0.M2.jar!/:2.3.0.M2]
k9-infotrygd-feed           | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.3.0.M2.jar!/:2.3.0.M2]
k9-infotrygd-feed           | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.3.0.M2.jar!/:2.3.0.M2]
k9-infotrygd-feed           | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot-2.3.0.M2.jar!/:2.3.0.M2]
k9-infotrygd-feed           | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.0.M2.jar!/:2.3.0.M2]
k9-infotrygd-feed           | 	at no.nav.k9.integrasjon.infotrygd.k9infotrygdfeed.K9InfotrygdFeedApplicationKt.main(K9InfotrygdFeedApplication.kt:13) ~[classes!/:0.0.1-SNAPSHOT]
k9-infotrygd-feed           | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
k9-infotrygd-feed           | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
k9-infotrygd-feed           | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
k9-infotrygd-feed           | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
k9-infotrygd-feed           | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[app.jar:0.0.1-SNAPSHOT]
k9-infotrygd-feed           | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:109) ~[app.jar:0.0.1-SNAPSHOT]
k9-infotrygd-feed           | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[app.jar:0.0.1-SNAPSHOT]
k9-infotrygd-feed           | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:93) ~[app.jar:0.0.1-SNAPSHOT]
k9-infotrygd-feed           | Caused by: org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
k9-infotrygd-feed           | 	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:126) ~[spring-boot-2.3.0.M2.jar!/:2.3.0.M2]
k9-infotrygd-feed           | 	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(TomcatWebServer.java:88) ~[spring-boot-2.3.0.M2.jar!/:2.3.0.M2]
k9-infotrygd-feed           | 	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getTomcatWebServer(TomcatServletWebServerFactory.java:438) ~[spring-boot-2.3.0.M2.jar!/:2.3.0.M2]
k9-infotrygd-feed           | 	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:191) ~[spring-boot-2.3.0.M2.jar!/:2.3.0.M2]
k9-infotrygd-feed           | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:180) ~[spring-boot-2.3.0.M2.jar!/:2.3.0.M2]
k9-infotrygd-feed           | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:153) ~[spring-boot-2.3.0.M2.jar!/:2.3.0.M2]
k9-infotrygd-feed           | 	... 17 common frames omitted
k9-infotrygd-feed           | Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'oidcTokenValidationFilterRegistrationBean' defined in class path resource [no/nav/security/token/support/spring/EnableJwtTokenValidationConfiguration.class]: Unsatisfied dependency expressed through method 'oidcTokenValidationFilterRegistrationBean' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'tokenValidationFilter' defined in class path resource [no/nav/security/token/support/spring/EnableJwtTokenValidationConfiguration.class]: Unsatisfied dependency expressed through method 'tokenValidationFilter' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'multiIssuerConfiguration' defined in class path resource [no/nav/security/token/support/spring/EnableJwtTokenValidationConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [no.nav.security.token.support.core.configuration.MultiIssuerConfiguration]: Factory method 'multiIssuerConfiguration' threw exception; nested exception is no.nav.security.token.support.core.exceptions.MetaDataNotAvailableException: could not retrieve metadata from url: http://vtp:8060/rest/isso/oauth2/.well-known/openid-configuration. received exception java.net.ConnectException: Connection refused (Connection refused)
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:539) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:211) ~[spring-boot-2.3.0.M2.jar!/:2.3.0.M2]
k9-infotrygd-feed           | 	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:202) ~[spring-boot-2.3.0.M2.jar!/:2.3.0.M2]
k9-infotrygd-feed           | 	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.addServletContextInitializerBeans(ServletContextInitializerBeans.java:96) ~[spring-boot-2.3.0.M2.jar!/:2.3.0.M2]
k9-infotrygd-feed           | 	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.<init>(ServletContextInitializerBeans.java:85) ~[spring-boot-2.3.0.M2.jar!/:2.3.0.M2]
k9-infotrygd-feed           | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getServletContextInitializerBeans(ServletWebServerApplicationContext.java:253) ~[spring-boot-2.3.0.M2.jar!/:2.3.0.M2]
k9-infotrygd-feed           | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.selfInitialize(ServletWebServerApplicationContext.java:227) ~[spring-boot-2.3.0.M2.jar!/:2.3.0.M2]
k9-infotrygd-feed           | 	at org.springframework.boot.web.embedded.tomcat.TomcatStarter.onStartup(TomcatStarter.java:53) ~[spring-boot-2.3.0.M2.jar!/:2.3.0.M2]
k9-infotrygd-feed           | 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5135) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
k9-infotrygd-feed           | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
k9-infotrygd-feed           | 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
k9-infotrygd-feed           | 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
k9-infotrygd-feed           | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
k9-infotrygd-feed           | 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
k9-infotrygd-feed           | 	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140) ~[na:na]
k9-infotrygd-feed           | 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
k9-infotrygd-feed           | 	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
k9-infotrygd-feed           | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
k9-infotrygd-feed           | 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
k9-infotrygd-feed           | 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
k9-infotrygd-feed           | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
k9-infotrygd-feed           | 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
k9-infotrygd-feed           | 	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140) ~[na:na]
k9-infotrygd-feed           | 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
k9-infotrygd-feed           | 	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
k9-infotrygd-feed           | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
k9-infotrygd-feed           | 	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
k9-infotrygd-feed           | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
k9-infotrygd-feed           | 	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
k9-infotrygd-feed           | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
k9-infotrygd-feed           | 	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:467) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
k9-infotrygd-feed           | 	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:107) ~[spring-boot-2.3.0.M2.jar!/:2.3.0.M2]
k9-infotrygd-feed           | 	... 22 common frames omitted
k9-infotrygd-feed           | Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'tokenValidationFilter' defined in class path resource [no/nav/security/token/support/spring/EnableJwtTokenValidationConfiguration.class]: Unsatisfied dependency expressed through method 'tokenValidationFilter' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'multiIssuerConfiguration' defined in class path resource [no/nav/security/token/support/spring/EnableJwtTokenValidationConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [no.nav.security.token.support.core.configuration.MultiIssuerConfiguration]: Factory method 'multiIssuerConfiguration' threw exception; nested exception is no.nav.security.token.support.core.exceptions.MetaDataNotAvailableException: could not retrieve metadata from url: http://vtp:8060/rest/isso/oauth2/.well-known/openid-configuration. received exception java.net.ConnectException: Connection refused (Connection refused)
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:539) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1287) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:885) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:789) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	... 62 common frames omitted
k9-infotrygd-feed           | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'multiIssuerConfiguration' defined in class path resource [no/nav/security/token/support/spring/EnableJwtTokenValidationConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [no.nav.security.token.support.core.configuration.MultiIssuerConfiguration]: Factory method 'multiIssuerConfiguration' threw exception; nested exception is no.nav.security.token.support.core.exceptions.MetaDataNotAvailableException: could not retrieve metadata from url: http://vtp:8060/rest/isso/oauth2/.well-known/openid-configuration. received exception java.net.ConnectException: Connection refused (Connection refused)
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:656) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:636) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1287) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:885) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:789) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	... 76 common frames omitted
k9-infotrygd-feed           | Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [no.nav.security.token.support.core.configuration.MultiIssuerConfiguration]: Factory method 'multiIssuerConfiguration' threw exception; nested exception is no.nav.security.token.support.core.exceptions.MetaDataNotAvailableException: could not retrieve metadata from url: http://vtp:8060/rest/isso/oauth2/.well-known/openid-configuration. received exception java.net.ConnectException: Connection refused (Connection refused)
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	... 90 common frames omitted
k9-infotrygd-feed           | Caused by: no.nav.security.token.support.core.exceptions.MetaDataNotAvailableException: could not retrieve metadata from url: http://vtp:8060/rest/isso/oauth2/.well-known/openid-configuration. received exception java.net.ConnectException: Connection refused (Connection refused)
k9-infotrygd-feed           | 	at no.nav.security.token.support.core.configuration.IssuerConfiguration.getProviderMetadata(IssuerConfiguration.java:121) ~[token-validation-core-1.1.4.jar!/:na]
k9-infotrygd-feed           | 	at no.nav.security.token.support.core.configuration.IssuerConfiguration.<init>(IssuerConfiguration.java:41) ~[token-validation-core-1.1.4.jar!/:na]
k9-infotrygd-feed           | 	at no.nav.security.token.support.core.configuration.IssuerConfiguration.<init>(IssuerConfiguration.java:32) ~[token-validation-core-1.1.4.jar!/:na]
k9-infotrygd-feed           | 	at no.nav.security.token.support.core.configuration.MultiIssuerConfiguration.createIssuerConfiguration(MultiIssuerConfiguration.java:65) ~[token-validation-core-1.1.4.jar!/:na]
k9-infotrygd-feed           | 	at no.nav.security.token.support.core.configuration.MultiIssuerConfiguration.loadIssuerConfigurations(MultiIssuerConfiguration.java:52) ~[token-validation-core-1.1.4.jar!/:na]
k9-infotrygd-feed           | 	at no.nav.security.token.support.core.configuration.MultiIssuerConfiguration.<init>(MultiIssuerConfiguration.java:25) ~[token-validation-core-1.1.4.jar!/:na]
k9-infotrygd-feed           | 	at no.nav.security.token.support.spring.EnableJwtTokenValidationConfiguration.multiIssuerConfiguration(EnableJwtTokenValidationConfiguration.java:77) ~[token-validation-spring-1.1.4.jar!/:na]
k9-infotrygd-feed           | 	at no.nav.security.token.support.spring.EnableJwtTokenValidationConfiguration$$EnhancerBySpringCGLIB$$ab702c21.CGLIB$multiIssuerConfiguration$4(<generated>) ~[token-validation-spring-1.1.4.jar!/:na]
k9-infotrygd-feed           | 	at no.nav.security.token.support.spring.EnableJwtTokenValidationConfiguration$$EnhancerBySpringCGLIB$$ab702c21$$FastClassBySpringCGLIB$$3088d512.invoke(<generated>) ~[token-validation-spring-1.1.4.jar!/:na]
k9-infotrygd-feed           | 	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	at no.nav.security.token.support.spring.EnableJwtTokenValidationConfiguration$$EnhancerBySpringCGLIB$$ab702c21.multiIssuerConfiguration(<generated>) ~[token-validation-spring-1.1.4.jar!/:na]
k9-infotrygd-feed           | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
k9-infotrygd-feed           | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
k9-infotrygd-feed           | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
k9-infotrygd-feed           | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
k9-infotrygd-feed           | 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
k9-infotrygd-feed           | 	... 91 common frames omitted
k9-infotrygd-feed           | Caused by: java.net.ConnectException: Connection refused (Connection refused)
k9-infotrygd-feed           | 	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:na]
k9-infotrygd-feed           | 	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[na:na]
k9-infotrygd-feed           | 	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[na:na]
k9-infotrygd-feed           | 	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[na:na]
k9-infotrygd-feed           | 	at java.base/java.net.Socket.connect(Socket.java:609) ~[na:na]
k9-infotrygd-feed           | 	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177) ~[na:na]
k9-infotrygd-feed           | 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474) ~[na:na]
k9-infotrygd-feed           | 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569) ~[na:na]
k9-infotrygd-feed           | 	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[na:na]
k9-infotrygd-feed           | 	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341) ~[na:na]
k9-infotrygd-feed           | 	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362) ~[na:na]
k9-infotrygd-feed           | 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1248) ~[na:na]
k9-infotrygd-feed           | 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187) ~[na:na]
k9-infotrygd-feed           | 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081) ~[na:na]
k9-infotrygd-feed           | 	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015) ~[na:na]
k9-infotrygd-feed           | 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587) ~[na:na]
k9-infotrygd-feed           | 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515) ~[na:na]
k9-infotrygd-feed           | 	at com.nimbusds.jose.util.DefaultResourceRetriever.getInputStream(DefaultResourceRetriever.java:249) ~[nimbus-jose-jwt-8.9.jar!/:8.9]
k9-infotrygd-feed           | 	at com.nimbusds.jose.util.DefaultResourceRetriever.retrieveResource(DefaultResourceRetriever.java:201) ~[nimbus-jose-jwt-8.9.jar!/:8.9]
k9-infotrygd-feed           | 	at no.nav.security.token.support.core.configuration.IssuerConfiguration.getProviderMetadata(IssuerConfiguration.java:119) ~[token-validation-core-1.1.4.jar!/:na]
k9-infotrygd-feed           | 	... 107 common frames omitted

```

**Comment by tronghn** [comment]
I og med at metadata er nødvendig for at tokenvalidering skal fungere så er denne oppførselen 'as intended'. Enten så vil applikasjonen feile ved oppstart, ellers så vil ikke valideringer fungere ved kjøretid hvis vi åpner for at det lastes inn senere.

Dette bør strengt tatt løses i testene/oppsettet deres.
