### ISSUE TITLE
Unødvendig (?) forsøk av token-validering gir feillogger.

### ISSUE THREAD

**Issue by flexable777** [navikt/token-support#922]
Vi har nylig oppgradert vår applikasjon til Spring Boot 3.3.x fra 3.2.5. Dette har ført til mye feillogging fra token-support.

Vi bruker Spring Boot og Server Sent Events (SSE) for å sende data fra server til klient.

Ved request til dette SSE-endepunktet så kalles token-support sitt filter som forventet, med en http request fra klienten.

Når/hvis klienten etterhvert lukker denne langlivede tilkoblingen, og vår app prøver å sende noe litt senere, så registreres det som en feil i Tomcat/Spring (broken pipe), men ikke så mye annet skjer (ingen feillogging).

Men, vi ser at med ny versjon av Spring Boot, og klienten lukket tilkoblingen, så sendes det nå en request med DispatcherType=ASYNC til deres filter, og dette gjør at vi får denne feilen:

```
java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
	at org.springframework.web.context.request.RequestContextHolder.currentRequestAttributes(RequestContextHolder.java:131) ~[spring-web-6.1.8.jar:6.1.8]
	at no.nav.security.token.support.spring.SpringTokenValidationContextHolder.setRequestAttribute(SpringTokenValidationContextHolder.kt:14) ~[token-validation-spring-5.0.1.jar:na]
	at no.nav.security.token.support.spring.SpringTokenValidationContextHolder.setTokenValidationContext(SpringTokenValidationContextHolder.kt:12) ~[token-validation-spring-5.0.1.jar:na]
	at no.nav.security.token.support.filter.JwtTokenValidationFilter.doTokenValidation(JwtTokenValidationFilter.kt:30) ~[token-validation-filter-5.0.1.jar:na]
	at no.nav.security.token.support.filter.JwtTokenValidationFilter.doFilter(JwtTokenValidationFilter.kt:20) ~[token-validation-filter-5.0.1.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.26.jar:10.1.26]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.26.jar:10.1.26]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:632) ~[tomcat-embed-core-10.1.26.jar:10.1.26]
	at org.apache.catalina.core.ApplicationDispatcher.doDispatch(ApplicationDispatcher.java:560) ~[tomcat-embed-core-10.1.26.jar:10.1.26]
	at org.apache.catalina.core.ApplicationDispatcher.dispatch(ApplicationDispatcher.java:531) ~[tomcat-embed-core-10.1.26.jar:10.1.26]
	at org.apache.catalina.core.AsyncContextImpl$AsyncRunnable.run(AsyncContextImpl.java:601) ~[tomcat-embed-core-10.1.26.jar:10.1.26]
	at org.apache.catalina.core.AsyncContextImpl.doInternalDispatch(AsyncContextImpl.java:344) ~[tomcat-embed-core-10.1.26.jar:10.1.26]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:165) ~[tomcat-embed-core-10.1.26.jar:10.1.26]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-10.1.26.jar:10.1.26]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483) ~[tomcat-embed-core-10.1.26.jar:10.1.26]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[tomcat-embed-core-10.1.26.jar:10.1.26]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-10.1.26.jar:10.1.26]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-10.1.26.jar:10.1.26]
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:239) ~[tomcat-embed-core-10.1.26.jar:10.1.26]
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:243) ~[tomcat-embed-core-10.1.26.jar:10.1.26]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:57) ~[tomcat-embed-core-10.1.26.jar:10.1.26]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:904) ~[tomcat-embed-core-10.1.26.jar:10.1.26]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741) ~[tomcat-embed-core-10.1.26.jar:10.1.26]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.26.jar:10.1.26]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190) ~[tomcat-embed-core-10.1.26.jar:10.1.26]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.26.jar:10.1.26]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) ~[tomcat-embed-core-10.1.26.jar:10.1.26]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
```

Dette er nok ikke så rart, fordi det faktisk skjer utenfor en web request.

Jeg er ikke helt sikker på beste løsningen, men man kunne kanskje tenkt seg å fange opp denne typen request, og ikke gå videre med valideringen? Denne requesten ser litt annerledes ut, og kan sjekkes med `request.dispatcherType == ASYNC`. I tillegg har den et attributt: `request.getAttribute("jakarta.servlet.error.exception")` som sier "broken pipe". Dette skjer som sagt etter klienten er borte, og validering av token ikke skulle være nødvendig?

Etter en del undersøkelser så fant jeg at denne endringen ble innført fra og med Spring Boot 3.2.6, da Tomcat ble oppgradert til 10.1.24 (https://tomcat.apache.org/tomcat-10.1-doc/changelog.html): 

> Correct error handling for asynchronous requests. If the application performs an dispatch during AsyncListener.onError() the dispatch is now performed rather than completing the request using the error page mechanism. (markt)

**Comment by jan-olaveide** [comment]
Beklager at dette har tatt så lang tid, hva tror du om [denne](https://github.com/navikt/token-support/pull/969)

**Comment by jan-olaveide** [comment]
Fikset i 5.0.11
